name: Build Debian Package

on:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  build_package:

    runs-on: ubuntu-latest
    container:
      image: debian:buster-slim

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: update source.list for debain archive
      run: sed -i -e 's/deb.debian.org/archive.debian.org/g' /etc/apt/sources.list

    - name: install build dependencies
      run: |
        apt-get update
        apt-get install -y dpkg-dev fakeroot
        apt-get build-dep -y .
      env:
        DEBIAN_FRONTEND: noninteractive

    - name: build package
      run: |
        dpkg-buildpackage -rfakeroot -us -uc

    - name: move artifacts
      run: |
        mkdir artifacts
        mv ../ocemr_* artifacts/

    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: debian-buster
        path: artifacts/ocemr_*
